language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  - TMUX_VERSION=1.8
  - TMUX_VERSION=1.9a
before_install:
  - sudo apt-get update -qq
  - export PIP_USE_MIRRORS=true
  - pip install coveralls
install:
  - "pip install -e ."
before_script:
  - sudo apt-get install -qq libevent-dev libncurses-dev
  - git clone git://git.code.sf.net/p/tmux/tmux-code tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure && make && sudo make install
  - cd ..
  - tmux -V
script: coverage run --source=tmuxp setup.py test
# script: python setup.py test
after_success:
  - coveralls
